layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: http://learnables.net
  # youtube: your_username

topics:
  - name: Meta-Learning
    web_url: http://learn2learn.net
    image_url: https://raw.githubusercontent.com/learnables/learn2learn/master/docs/source/assets/img/learn2learn.png

  - name: Reinforcement Learning
    web_url: http://cherry-rl.net
    image_url: https://raw.githubusercontent.com/learnables/cherry/master/docs/source/assets/img/cherry.png
